using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using AnimalTheoryRoyale.Data;
using AnimalTheoryRoyale.Models;

namespace AnimalTheoryRoyale.Controllers;

[ApiController]
[Route("api/[controller]")]
public class SeedController : ControllerBase
{
    private readonly ApplicationDbContext _db;
    public SeedController(ApplicationDbContext db) => _db = db;

    [HttpPost("questions")]
    public async Task<IActionResult> SeedQuestions()
    {

        // Ensure topics
        var topicNames = new[]
        {
            "Nền tảng đường lối 1930",
            "Cao trào và phục hồi 1930–1935",
            "Phong trào dân chủ 1936–1939",
            "Chuyển hướng chiến lược 1939–1941",
            "Việt Minh và Cách mạng Tháng Tám 1945",
        };
        foreach (var tn in topicNames)
            if (!await _db.Topics.AnyAsync(t => t.Name == tn))
                _db.Topics.Add(new Topic { Name = tn, Description = tn });
        await _db.SaveChangesAsync();
        var topics = await _db.Topics.ToDictionaryAsync(t => t.Name, t => t.Id);


        var qs = new (int tid, string diff, string content, string expl, string[] opts, int ci)[]
        {
            (topics[topicNames[0]], "Easy", "Cương lĩnh chính trị đầu tiên do ai soạn thảo?", "Nguyễn Ái Quốc trực tiếp soạn thảo và thông qua tại Hội nghị thành lập Đảng 1930.", new[] { "Nguyễn Ái Quốc", "Trần Phú", "Lê Hồng Phong", "Hà Huy Tập" }, 0),
            (topics[topicNames[0]], "Easy", "Nhiệm vụ hàng đầu của cách mạng Đông Dương được xác định trong Cương lĩnh đầu tiên là gì?", "Vấn đề dân tộc được Nguyễn Ái Quốc đặt lên hàng đầu.", new[] { "Đánh đổ đế quốc Pháp giành độc lập", "Cách mạng ruộng đất", "Đánh đổ phong kiến", "Đấu tranh đòi quyền lợi kinh tế" }, 0),
            (topics[topicNames[0]], "Easy", "Seed Q3 - Nền tảng đường lối 1930: Sự kiện nào diễn ra vào thời điểm 3?", "Đây là điểm mấu chốt để hiểu về Nền tảng đường lối 1930.", new[] { "Lựa chọn đúng về lịch sử Đảng 3", "Lựa chọn sai A 3", "Lựa chọn sai B 3", "Lựa chọn sai C 3" }, 0),
            (topics[topicNames[0]], "Easy", "Seed Q4 - Nền tảng đường lối 1930: Sự kiện nào diễn ra vào thời điểm 4?", "Đây là điểm mấu chốt để hiểu về Nền tảng đường lối 1930.", new[] { "Lựa chọn đúng về lịch sử Đảng 4", "Lựa chọn sai A 4", "Lựa chọn sai B 4", "Lựa chọn sai C 4" }, 0),
            (topics[topicNames[0]], "Easy", "Seed Q5 - Nền tảng đường lối 1930: Sự kiện nào diễn ra vào thời điểm 5?", "Đây là điểm mấu chốt để hiểu về Nền tảng đường lối 1930.", new[] { "Lựa chọn đúng về lịch sử Đảng 5", "Lựa chọn sai A 5", "Lựa chọn sai B 5", "Lựa chọn sai C 5" }, 0),
            (topics[topicNames[0]], "Easy", "Seed Q6 - Nền tảng đường lối 1930: Sự kiện nào diễn ra vào thời điểm 6?", "Đây là điểm mấu chốt để hiểu về Nền tảng đường lối 1930.", new[] { "Lựa chọn đúng về lịch sử Đảng 6", "Lựa chọn sai A 6", "Lựa chọn sai B 6", "Lựa chọn sai C 6" }, 0),
            (topics[topicNames[0]], "Easy", "Seed Q7 - Nền tảng đường lối 1930: Sự kiện nào diễn ra vào thời điểm 7?", "Đây là điểm mấu chốt để hiểu về Nền tảng đường lối 1930.", new[] { "Lựa chọn đúng về lịch sử Đảng 7", "Lựa chọn sai A 7", "Lựa chọn sai B 7", "Lựa chọn sai C 7" }, 0),
            (topics[topicNames[0]], "Medium", "Seed Q8 - Nền tảng đường lối 1930: Sự kiện tiêu biểu số 8 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Nền tảng đường lối 1930.", new[] { "Lựa chọn đúng về lịch sử Đảng 8", "Lựa chọn sai A 8", "Lựa chọn sai B 8", "Lựa chọn sai C 8" }, 0),
            (topics[topicNames[0]], "Medium", "Seed Q9 - Nền tảng đường lối 1930: Sự kiện tiêu biểu số 9 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Nền tảng đường lối 1930.", new[] { "Lựa chọn đúng về lịch sử Đảng 9", "Lựa chọn sai A 9", "Lựa chọn sai B 9", "Lựa chọn sai C 9" }, 0),
            (topics[topicNames[0]], "Medium", "Seed Q10 - Nền tảng đường lối 1930: Sự kiện tiêu biểu số 10 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Nền tảng đường lối 1930.", new[] { "Lựa chọn đúng về lịch sử Đảng 10", "Lựa chọn sai A 10", "Lựa chọn sai B 10", "Lựa chọn sai C 10" }, 0),
            (topics[topicNames[0]], "Medium", "Seed Q11 - Nền tảng đường lối 1930: Sự kiện tiêu biểu số 11 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Nền tảng đường lối 1930.", new[] { "Lựa chọn đúng về lịch sử Đảng 11", "Lựa chọn sai A 11", "Lựa chọn sai B 11", "Lựa chọn sai C 11" }, 0),
            (topics[topicNames[0]], "Medium", "Seed Q12 - Nền tảng đường lối 1930: Sự kiện tiêu biểu số 12 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Nền tảng đường lối 1930.", new[] { "Lựa chọn đúng về lịch sử Đảng 12", "Lựa chọn sai A 12", "Lựa chọn sai B 12", "Lựa chọn sai C 12" }, 0),
            (topics[topicNames[0]], "Medium", "Seed Q13 - Nền tảng đường lối 1930: Sự kiện tiêu biểu số 13 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Nền tảng đường lối 1930.", new[] { "Lựa chọn đúng về lịch sử Đảng 13", "Lựa chọn sai A 13", "Lựa chọn sai B 13", "Lựa chọn sai C 13" }, 0),
            (topics[topicNames[0]], "Medium", "Seed Q14 - Nền tảng đường lối 1930: Sự kiện tiêu biểu số 14 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Nền tảng đường lối 1930.", new[] { "Lựa chọn đúng về lịch sử Đảng 14", "Lựa chọn sai A 14", "Lựa chọn sai B 14", "Lựa chọn sai C 14" }, 0),
            (topics[topicNames[0]], "Medium", "Seed Q15 - Nền tảng đường lối 1930: Sự kiện tiêu biểu số 15 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Nền tảng đường lối 1930.", new[] { "Lựa chọn đúng về lịch sử Đảng 15", "Lựa chọn sai A 15", "Lựa chọn sai B 15", "Lựa chọn sai C 15" }, 0),
            (topics[topicNames[0]], "Hard", "Seed Q16 - Nền tảng đường lối 1930: Vì sao quyết định này phản ánh năng lực lãnh đạo tài tình của Đảng?", "Đây là điểm mấu chốt để hiểu về Nền tảng đường lối 1930.", new[] { "Lựa chọn đúng về lịch sử Đảng 16", "Lựa chọn sai A 16", "Lựa chọn sai B 16", "Lựa chọn sai C 16" }, 0),
            (topics[topicNames[0]], "Hard", "Seed Q17 - Nền tảng đường lối 1930: Vì sao quyết định này phản ánh năng lực lãnh đạo tài tình của Đảng?", "Đây là điểm mấu chốt để hiểu về Nền tảng đường lối 1930.", new[] { "Lựa chọn đúng về lịch sử Đảng 17", "Lựa chọn sai A 17", "Lựa chọn sai B 17", "Lựa chọn sai C 17" }, 0),
            (topics[topicNames[0]], "Hard", "Seed Q18 - Nền tảng đường lối 1930: Vì sao quyết định này phản ánh năng lực lãnh đạo tài tình của Đảng?", "Đây là điểm mấu chốt để hiểu về Nền tảng đường lối 1930.", new[] { "Lựa chọn đúng về lịch sử Đảng 18", "Lựa chọn sai A 18", "Lựa chọn sai B 18", "Lựa chọn sai C 18" }, 0),
            (topics[topicNames[0]], "Hard", "Seed Q19 - Nền tảng đường lối 1930: Vì sao quyết định này phản ánh năng lực lãnh đạo tài tình của Đảng?", "Đây là điểm mấu chốt để hiểu về Nền tảng đường lối 1930.", new[] { "Lựa chọn đúng về lịch sử Đảng 19", "Lựa chọn sai A 19", "Lựa chọn sai B 19", "Lựa chọn sai C 19" }, 0),
            (topics[topicNames[0]], "Hard", "Seed Q20 - Nền tảng đường lối 1930: Vì sao quyết định này phản ánh năng lực lãnh đạo tài tình của Đảng?", "Đây là điểm mấu chốt để hiểu về Nền tảng đường lối 1930.", new[] { "Lựa chọn đúng về lịch sử Đảng 20", "Lựa chọn sai A 20", "Lựa chọn sai B 20", "Lựa chọn sai C 20" }, 0),
            (topics[topicNames[1]], "Easy", "Seed Q21 - Cao trào và phục hồi 1930–1935: Sự kiện nào diễn ra vào thời điểm 1?", "Đây là điểm mấu chốt để hiểu về Cao trào và phục hồi 1930–1935.", new[] { "Lựa chọn đúng về lịch sử Đảng 1", "Lựa chọn sai A 1", "Lựa chọn sai B 1", "Lựa chọn sai C 1" }, 0),
            (topics[topicNames[1]], "Easy", "Seed Q22 - Cao trào và phục hồi 1930–1935: Sự kiện nào diễn ra vào thời điểm 2?", "Đây là điểm mấu chốt để hiểu về Cao trào và phục hồi 1930–1935.", new[] { "Lựa chọn đúng về lịch sử Đảng 2", "Lựa chọn sai A 2", "Lựa chọn sai B 2", "Lựa chọn sai C 2" }, 0),
            (topics[topicNames[1]], "Easy", "Seed Q23 - Cao trào và phục hồi 1930–1935: Sự kiện nào diễn ra vào thời điểm 3?", "Đây là điểm mấu chốt để hiểu về Cao trào và phục hồi 1930–1935.", new[] { "Lựa chọn đúng về lịch sử Đảng 3", "Lựa chọn sai A 3", "Lựa chọn sai B 3", "Lựa chọn sai C 3" }, 0),
            (topics[topicNames[1]], "Easy", "Seed Q24 - Cao trào và phục hồi 1930–1935: Sự kiện nào diễn ra vào thời điểm 4?", "Đây là điểm mấu chốt để hiểu về Cao trào và phục hồi 1930–1935.", new[] { "Lựa chọn đúng về lịch sử Đảng 4", "Lựa chọn sai A 4", "Lựa chọn sai B 4", "Lựa chọn sai C 4" }, 0),
            (topics[topicNames[1]], "Easy", "Seed Q25 - Cao trào và phục hồi 1930–1935: Sự kiện nào diễn ra vào thời điểm 5?", "Đây là điểm mấu chốt để hiểu về Cao trào và phục hồi 1930–1935.", new[] { "Lựa chọn đúng về lịch sử Đảng 5", "Lựa chọn sai A 5", "Lựa chọn sai B 5", "Lựa chọn sai C 5" }, 0),
            (topics[topicNames[1]], "Easy", "Seed Q26 - Cao trào và phục hồi 1930–1935: Sự kiện nào diễn ra vào thời điểm 6?", "Đây là điểm mấu chốt để hiểu về Cao trào và phục hồi 1930–1935.", new[] { "Lựa chọn đúng về lịch sử Đảng 6", "Lựa chọn sai A 6", "Lựa chọn sai B 6", "Lựa chọn sai C 6" }, 0),
            (topics[topicNames[1]], "Easy", "Seed Q27 - Cao trào và phục hồi 1930–1935: Sự kiện nào diễn ra vào thời điểm 7?", "Đây là điểm mấu chốt để hiểu về Cao trào và phục hồi 1930–1935.", new[] { "Lựa chọn đúng về lịch sử Đảng 7", "Lựa chọn sai A 7", "Lựa chọn sai B 7", "Lựa chọn sai C 7" }, 0),
            (topics[topicNames[1]], "Medium", "Seed Q28 - Cao trào và phục hồi 1930–1935: Sự kiện tiêu biểu số 8 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Cao trào và phục hồi 1930–1935.", new[] { "Lựa chọn đúng về lịch sử Đảng 8", "Lựa chọn sai A 8", "Lựa chọn sai B 8", "Lựa chọn sai C 8" }, 0),
            (topics[topicNames[1]], "Medium", "Seed Q29 - Cao trào và phục hồi 1930–1935: Sự kiện tiêu biểu số 9 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Cao trào và phục hồi 1930–1935.", new[] { "Lựa chọn đúng về lịch sử Đảng 9", "Lựa chọn sai A 9", "Lựa chọn sai B 9", "Lựa chọn sai C 9" }, 0),
            (topics[topicNames[1]], "Medium", "Seed Q30 - Cao trào và phục hồi 1930–1935: Sự kiện tiêu biểu số 10 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Cao trào và phục hồi 1930–1935.", new[] { "Lựa chọn đúng về lịch sử Đảng 10", "Lựa chọn sai A 10", "Lựa chọn sai B 10", "Lựa chọn sai C 10" }, 0),
            (topics[topicNames[1]], "Medium", "Seed Q31 - Cao trào và phục hồi 1930–1935: Sự kiện tiêu biểu số 11 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Cao trào và phục hồi 1930–1935.", new[] { "Lựa chọn đúng về lịch sử Đảng 11", "Lựa chọn sai A 11", "Lựa chọn sai B 11", "Lựa chọn sai C 11" }, 0),
            (topics[topicNames[1]], "Medium", "Seed Q32 - Cao trào và phục hồi 1930–1935: Sự kiện tiêu biểu số 12 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Cao trào và phục hồi 1930–1935.", new[] { "Lựa chọn đúng về lịch sử Đảng 12", "Lựa chọn sai A 12", "Lựa chọn sai B 12", "Lựa chọn sai C 12" }, 0),
            (topics[topicNames[1]], "Medium", "Seed Q33 - Cao trào và phục hồi 1930–1935: Sự kiện tiêu biểu số 13 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Cao trào và phục hồi 1930–1935.", new[] { "Lựa chọn đúng về lịch sử Đảng 13", "Lựa chọn sai A 13", "Lựa chọn sai B 13", "Lựa chọn sai C 13" }, 0),
            (topics[topicNames[1]], "Medium", "Seed Q34 - Cao trào và phục hồi 1930–1935: Sự kiện tiêu biểu số 14 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Cao trào và phục hồi 1930–1935.", new[] { "Lựa chọn đúng về lịch sử Đảng 14", "Lựa chọn sai A 14", "Lựa chọn sai B 14", "Lựa chọn sai C 14" }, 0),
            (topics[topicNames[1]], "Medium", "Seed Q35 - Cao trào và phục hồi 1930–1935: Sự kiện tiêu biểu số 15 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Cao trào và phục hồi 1930–1935.", new[] { "Lựa chọn đúng về lịch sử Đảng 15", "Lựa chọn sai A 15", "Lựa chọn sai B 15", "Lựa chọn sai C 15" }, 0),
            (topics[topicNames[1]], "Hard", "Seed Q36 - Cao trào và phục hồi 1930–1935: Vì sao quyết định này phản ánh năng lực lãnh đạo tài tình của Đảng?", "Đây là điểm mấu chốt để hiểu về Cao trào và phục hồi 1930–1935.", new[] { "Lựa chọn đúng về lịch sử Đảng 16", "Lựa chọn sai A 16", "Lựa chọn sai B 16", "Lựa chọn sai C 16" }, 0),
            (topics[topicNames[1]], "Hard", "Seed Q37 - Cao trào và phục hồi 1930–1935: Vì sao quyết định này phản ánh năng lực lãnh đạo tài tình của Đảng?", "Đây là điểm mấu chốt để hiểu về Cao trào và phục hồi 1930–1935.", new[] { "Lựa chọn đúng về lịch sử Đảng 17", "Lựa chọn sai A 17", "Lựa chọn sai B 17", "Lựa chọn sai C 17" }, 0),
            (topics[topicNames[1]], "Hard", "Seed Q38 - Cao trào và phục hồi 1930–1935: Vì sao quyết định này phản ánh năng lực lãnh đạo tài tình của Đảng?", "Đây là điểm mấu chốt để hiểu về Cao trào và phục hồi 1930–1935.", new[] { "Lựa chọn đúng về lịch sử Đảng 18", "Lựa chọn sai A 18", "Lựa chọn sai B 18", "Lựa chọn sai C 18" }, 0),
            (topics[topicNames[1]], "Hard", "Seed Q39 - Cao trào và phục hồi 1930–1935: Vì sao quyết định này phản ánh năng lực lãnh đạo tài tình của Đảng?", "Đây là điểm mấu chốt để hiểu về Cao trào và phục hồi 1930–1935.", new[] { "Lựa chọn đúng về lịch sử Đảng 19", "Lựa chọn sai A 19", "Lựa chọn sai B 19", "Lựa chọn sai C 19" }, 0),
            (topics[topicNames[1]], "Hard", "Seed Q40 - Cao trào và phục hồi 1930–1935: Vì sao quyết định này phản ánh năng lực lãnh đạo tài tình của Đảng?", "Đây là điểm mấu chốt để hiểu về Cao trào và phục hồi 1930–1935.", new[] { "Lựa chọn đúng về lịch sử Đảng 20", "Lựa chọn sai A 20", "Lựa chọn sai B 20", "Lựa chọn sai C 20" }, 0),
            (topics[topicNames[2]], "Easy", "Seed Q41 - Phong trào dân chủ 1936–1939: Sự kiện nào diễn ra vào thời điểm 1?", "Đây là điểm mấu chốt để hiểu về Phong trào dân chủ 1936–1939.", new[] { "Lựa chọn đúng về lịch sử Đảng 1", "Lựa chọn sai A 1", "Lựa chọn sai B 1", "Lựa chọn sai C 1" }, 0),
            (topics[topicNames[2]], "Easy", "Seed Q42 - Phong trào dân chủ 1936–1939: Sự kiện nào diễn ra vào thời điểm 2?", "Đây là điểm mấu chốt để hiểu về Phong trào dân chủ 1936–1939.", new[] { "Lựa chọn đúng về lịch sử Đảng 2", "Lựa chọn sai A 2", "Lựa chọn sai B 2", "Lựa chọn sai C 2" }, 0),
            (topics[topicNames[2]], "Easy", "Seed Q43 - Phong trào dân chủ 1936–1939: Sự kiện nào diễn ra vào thời điểm 3?", "Đây là điểm mấu chốt để hiểu về Phong trào dân chủ 1936–1939.", new[] { "Lựa chọn đúng về lịch sử Đảng 3", "Lựa chọn sai A 3", "Lựa chọn sai B 3", "Lựa chọn sai C 3" }, 0),
            (topics[topicNames[2]], "Easy", "Seed Q44 - Phong trào dân chủ 1936–1939: Sự kiện nào diễn ra vào thời điểm 4?", "Đây là điểm mấu chốt để hiểu về Phong trào dân chủ 1936–1939.", new[] { "Lựa chọn đúng về lịch sử Đảng 4", "Lựa chọn sai A 4", "Lựa chọn sai B 4", "Lựa chọn sai C 4" }, 0),
            (topics[topicNames[2]], "Easy", "Seed Q45 - Phong trào dân chủ 1936–1939: Sự kiện nào diễn ra vào thời điểm 5?", "Đây là điểm mấu chốt để hiểu về Phong trào dân chủ 1936–1939.", new[] { "Lựa chọn đúng về lịch sử Đảng 5", "Lựa chọn sai A 5", "Lựa chọn sai B 5", "Lựa chọn sai C 5" }, 0),
            (topics[topicNames[2]], "Easy", "Seed Q46 - Phong trào dân chủ 1936–1939: Sự kiện nào diễn ra vào thời điểm 6?", "Đây là điểm mấu chốt để hiểu về Phong trào dân chủ 1936–1939.", new[] { "Lựa chọn đúng về lịch sử Đảng 6", "Lựa chọn sai A 6", "Lựa chọn sai B 6", "Lựa chọn sai C 6" }, 0),
            (topics[topicNames[2]], "Easy", "Seed Q47 - Phong trào dân chủ 1936–1939: Sự kiện nào diễn ra vào thời điểm 7?", "Đây là điểm mấu chốt để hiểu về Phong trào dân chủ 1936–1939.", new[] { "Lựa chọn đúng về lịch sử Đảng 7", "Lựa chọn sai A 7", "Lựa chọn sai B 7", "Lựa chọn sai C 7" }, 0),
            (topics[topicNames[2]], "Medium", "Seed Q48 - Phong trào dân chủ 1936–1939: Sự kiện tiêu biểu số 8 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Phong trào dân chủ 1936–1939.", new[] { "Lựa chọn đúng về lịch sử Đảng 8", "Lựa chọn sai A 8", "Lựa chọn sai B 8", "Lựa chọn sai C 8" }, 0),
            (topics[topicNames[2]], "Medium", "Seed Q49 - Phong trào dân chủ 1936–1939: Sự kiện tiêu biểu số 9 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Phong trào dân chủ 1936–1939.", new[] { "Lựa chọn đúng về lịch sử Đảng 9", "Lựa chọn sai A 9", "Lựa chọn sai B 9", "Lựa chọn sai C 9" }, 0),
            (topics[topicNames[2]], "Medium", "Seed Q50 - Phong trào dân chủ 1936–1939: Sự kiện tiêu biểu số 10 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Phong trào dân chủ 1936–1939.", new[] { "Lựa chọn đúng về lịch sử Đảng 10", "Lựa chọn sai A 10", "Lựa chọn sai B 10", "Lựa chọn sai C 10" }, 0),
            (topics[topicNames[2]], "Medium", "Seed Q51 - Phong trào dân chủ 1936–1939: Sự kiện tiêu biểu số 11 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Phong trào dân chủ 1936–1939.", new[] { "Lựa chọn đúng về lịch sử Đảng 11", "Lựa chọn sai A 11", "Lựa chọn sai B 11", "Lựa chọn sai C 11" }, 0),
            (topics[topicNames[2]], "Medium", "Seed Q52 - Phong trào dân chủ 1936–1939: Sự kiện tiêu biểu số 12 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Phong trào dân chủ 1936–1939.", new[] { "Lựa chọn đúng về lịch sử Đảng 12", "Lựa chọn sai A 12", "Lựa chọn sai B 12", "Lựa chọn sai C 12" }, 0),
            (topics[topicNames[2]], "Medium", "Seed Q53 - Phong trào dân chủ 1936–1939: Sự kiện tiêu biểu số 13 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Phong trào dân chủ 1936–1939.", new[] { "Lựa chọn đúng về lịch sử Đảng 13", "Lựa chọn sai A 13", "Lựa chọn sai B 13", "Lựa chọn sai C 13" }, 0),
            (topics[topicNames[2]], "Medium", "Seed Q54 - Phong trào dân chủ 1936–1939: Sự kiện tiêu biểu số 14 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Phong trào dân chủ 1936–1939.", new[] { "Lựa chọn đúng về lịch sử Đảng 14", "Lựa chọn sai A 14", "Lựa chọn sai B 14", "Lựa chọn sai C 14" }, 0),
            (topics[topicNames[2]], "Medium", "Seed Q55 - Phong trào dân chủ 1936–1939: Sự kiện tiêu biểu số 15 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Phong trào dân chủ 1936–1939.", new[] { "Lựa chọn đúng về lịch sử Đảng 15", "Lựa chọn sai A 15", "Lựa chọn sai B 15", "Lựa chọn sai C 15" }, 0),
            (topics[topicNames[2]], "Hard", "Seed Q56 - Phong trào dân chủ 1936–1939: Vì sao quyết định này phản ánh năng lực lãnh đạo tài tình của Đảng?", "Đây là điểm mấu chốt để hiểu về Phong trào dân chủ 1936–1939.", new[] { "Lựa chọn đúng về lịch sử Đảng 16", "Lựa chọn sai A 16", "Lựa chọn sai B 16", "Lựa chọn sai C 16" }, 0),
            (topics[topicNames[2]], "Hard", "Seed Q57 - Phong trào dân chủ 1936–1939: Vì sao quyết định này phản ánh năng lực lãnh đạo tài tình của Đảng?", "Đây là điểm mấu chốt để hiểu về Phong trào dân chủ 1936–1939.", new[] { "Lựa chọn đúng về lịch sử Đảng 17", "Lựa chọn sai A 17", "Lựa chọn sai B 17", "Lựa chọn sai C 17" }, 0),
            (topics[topicNames[2]], "Hard", "Seed Q58 - Phong trào dân chủ 1936–1939: Vì sao quyết định này phản ánh năng lực lãnh đạo tài tình của Đảng?", "Đây là điểm mấu chốt để hiểu về Phong trào dân chủ 1936–1939.", new[] { "Lựa chọn đúng về lịch sử Đảng 18", "Lựa chọn sai A 18", "Lựa chọn sai B 18", "Lựa chọn sai C 18" }, 0),
            (topics[topicNames[2]], "Hard", "Seed Q59 - Phong trào dân chủ 1936–1939: Vì sao quyết định này phản ánh năng lực lãnh đạo tài tình của Đảng?", "Đây là điểm mấu chốt để hiểu về Phong trào dân chủ 1936–1939.", new[] { "Lựa chọn đúng về lịch sử Đảng 19", "Lựa chọn sai A 19", "Lựa chọn sai B 19", "Lựa chọn sai C 19" }, 0),
            (topics[topicNames[2]], "Hard", "Seed Q60 - Phong trào dân chủ 1936–1939: Vì sao quyết định này phản ánh năng lực lãnh đạo tài tình của Đảng?", "Đây là điểm mấu chốt để hiểu về Phong trào dân chủ 1936–1939.", new[] { "Lựa chọn đúng về lịch sử Đảng 20", "Lựa chọn sai A 20", "Lựa chọn sai B 20", "Lựa chọn sai C 20" }, 0),
            (topics[topicNames[3]], "Easy", "Seed Q61 - Chuyển hướng chiến lược 1939–1941: Sự kiện nào diễn ra vào thời điểm 1?", "Đây là điểm mấu chốt để hiểu về Chuyển hướng chiến lược 1939–1941.", new[] { "Lựa chọn đúng về lịch sử Đảng 1", "Lựa chọn sai A 1", "Lựa chọn sai B 1", "Lựa chọn sai C 1" }, 0),
            (topics[topicNames[3]], "Easy", "Seed Q62 - Chuyển hướng chiến lược 1939–1941: Sự kiện nào diễn ra vào thời điểm 2?", "Đây là điểm mấu chốt để hiểu về Chuyển hướng chiến lược 1939–1941.", new[] { "Lựa chọn đúng về lịch sử Đảng 2", "Lựa chọn sai A 2", "Lựa chọn sai B 2", "Lựa chọn sai C 2" }, 0),
            (topics[topicNames[3]], "Easy", "Seed Q63 - Chuyển hướng chiến lược 1939–1941: Sự kiện nào diễn ra vào thời điểm 3?", "Đây là điểm mấu chốt để hiểu về Chuyển hướng chiến lược 1939–1941.", new[] { "Lựa chọn đúng về lịch sử Đảng 3", "Lựa chọn sai A 3", "Lựa chọn sai B 3", "Lựa chọn sai C 3" }, 0),
            (topics[topicNames[3]], "Easy", "Seed Q64 - Chuyển hướng chiến lược 1939–1941: Sự kiện nào diễn ra vào thời điểm 4?", "Đây là điểm mấu chốt để hiểu về Chuyển hướng chiến lược 1939–1941.", new[] { "Lựa chọn đúng về lịch sử Đảng 4", "Lựa chọn sai A 4", "Lựa chọn sai B 4", "Lựa chọn sai C 4" }, 0),
            (topics[topicNames[3]], "Easy", "Seed Q65 - Chuyển hướng chiến lược 1939–1941: Sự kiện nào diễn ra vào thời điểm 5?", "Đây là điểm mấu chốt để hiểu về Chuyển hướng chiến lược 1939–1941.", new[] { "Lựa chọn đúng về lịch sử Đảng 5", "Lựa chọn sai A 5", "Lựa chọn sai B 5", "Lựa chọn sai C 5" }, 0),
            (topics[topicNames[3]], "Easy", "Seed Q66 - Chuyển hướng chiến lược 1939–1941: Sự kiện nào diễn ra vào thời điểm 6?", "Đây là điểm mấu chốt để hiểu về Chuyển hướng chiến lược 1939–1941.", new[] { "Lựa chọn đúng về lịch sử Đảng 6", "Lựa chọn sai A 6", "Lựa chọn sai B 6", "Lựa chọn sai C 6" }, 0),
            (topics[topicNames[3]], "Easy", "Seed Q67 - Chuyển hướng chiến lược 1939–1941: Sự kiện nào diễn ra vào thời điểm 7?", "Đây là điểm mấu chốt để hiểu về Chuyển hướng chiến lược 1939–1941.", new[] { "Lựa chọn đúng về lịch sử Đảng 7", "Lựa chọn sai A 7", "Lựa chọn sai B 7", "Lựa chọn sai C 7" }, 0),
            (topics[topicNames[3]], "Medium", "Seed Q68 - Chuyển hướng chiến lược 1939–1941: Sự kiện tiêu biểu số 8 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Chuyển hướng chiến lược 1939–1941.", new[] { "Lựa chọn đúng về lịch sử Đảng 8", "Lựa chọn sai A 8", "Lựa chọn sai B 8", "Lựa chọn sai C 8" }, 0),
            (topics[topicNames[3]], "Medium", "Seed Q69 - Chuyển hướng chiến lược 1939–1941: Sự kiện tiêu biểu số 9 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Chuyển hướng chiến lược 1939–1941.", new[] { "Lựa chọn đúng về lịch sử Đảng 9", "Lựa chọn sai A 9", "Lựa chọn sai B 9", "Lựa chọn sai C 9" }, 0),
            (topics[topicNames[3]], "Medium", "Seed Q70 - Chuyển hướng chiến lược 1939–1941: Sự kiện tiêu biểu số 10 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Chuyển hướng chiến lược 1939–1941.", new[] { "Lựa chọn đúng về lịch sử Đảng 10", "Lựa chọn sai A 10", "Lựa chọn sai B 10", "Lựa chọn sai C 10" }, 0),
            (topics[topicNames[3]], "Medium", "Seed Q71 - Chuyển hướng chiến lược 1939–1941: Sự kiện tiêu biểu số 11 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Chuyển hướng chiến lược 1939–1941.", new[] { "Lựa chọn đúng về lịch sử Đảng 11", "Lựa chọn sai A 11", "Lựa chọn sai B 11", "Lựa chọn sai C 11" }, 0),
            (topics[topicNames[3]], "Medium", "Seed Q72 - Chuyển hướng chiến lược 1939–1941: Sự kiện tiêu biểu số 12 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Chuyển hướng chiến lược 1939–1941.", new[] { "Lựa chọn đúng về lịch sử Đảng 12", "Lựa chọn sai A 12", "Lựa chọn sai B 12", "Lựa chọn sai C 12" }, 0),
            (topics[topicNames[3]], "Medium", "Seed Q73 - Chuyển hướng chiến lược 1939–1941: Sự kiện tiêu biểu số 13 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Chuyển hướng chiến lược 1939–1941.", new[] { "Lựa chọn đúng về lịch sử Đảng 13", "Lựa chọn sai A 13", "Lựa chọn sai B 13", "Lựa chọn sai C 13" }, 0),
            (topics[topicNames[3]], "Medium", "Seed Q74 - Chuyển hướng chiến lược 1939–1941: Sự kiện tiêu biểu số 14 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Chuyển hướng chiến lược 1939–1941.", new[] { "Lựa chọn đúng về lịch sử Đảng 14", "Lựa chọn sai A 14", "Lựa chọn sai B 14", "Lựa chọn sai C 14" }, 0),
            (topics[topicNames[3]], "Medium", "Seed Q75 - Chuyển hướng chiến lược 1939–1941: Sự kiện tiêu biểu số 15 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Chuyển hướng chiến lược 1939–1941.", new[] { "Lựa chọn đúng về lịch sử Đảng 15", "Lựa chọn sai A 15", "Lựa chọn sai B 15", "Lựa chọn sai C 15" }, 0),
            (topics[topicNames[3]], "Hard", "Seed Q76 - Chuyển hướng chiến lược 1939–1941: Vì sao quyết định này phản ánh năng lực lãnh đạo tài tình của Đảng?", "Đây là điểm mấu chốt để hiểu về Chuyển hướng chiến lược 1939–1941.", new[] { "Lựa chọn đúng về lịch sử Đảng 16", "Lựa chọn sai A 16", "Lựa chọn sai B 16", "Lựa chọn sai C 16" }, 0),
            (topics[topicNames[3]], "Hard", "Seed Q77 - Chuyển hướng chiến lược 1939–1941: Vì sao quyết định này phản ánh năng lực lãnh đạo tài tình của Đảng?", "Đây là điểm mấu chốt để hiểu về Chuyển hướng chiến lược 1939–1941.", new[] { "Lựa chọn đúng về lịch sử Đảng 17", "Lựa chọn sai A 17", "Lựa chọn sai B 17", "Lựa chọn sai C 17" }, 0),
            (topics[topicNames[3]], "Hard", "Seed Q78 - Chuyển hướng chiến lược 1939–1941: Vì sao quyết định này phản ánh năng lực lãnh đạo tài tình của Đảng?", "Đây là điểm mấu chốt để hiểu về Chuyển hướng chiến lược 1939–1941.", new[] { "Lựa chọn đúng về lịch sử Đảng 18", "Lựa chọn sai A 18", "Lựa chọn sai B 18", "Lựa chọn sai C 18" }, 0),
            (topics[topicNames[3]], "Hard", "Seed Q79 - Chuyển hướng chiến lược 1939–1941: Vì sao quyết định này phản ánh năng lực lãnh đạo tài tình của Đảng?", "Đây là điểm mấu chốt để hiểu về Chuyển hướng chiến lược 1939–1941.", new[] { "Lựa chọn đúng về lịch sử Đảng 19", "Lựa chọn sai A 19", "Lựa chọn sai B 19", "Lựa chọn sai C 19" }, 0),
            (topics[topicNames[3]], "Hard", "Seed Q80 - Chuyển hướng chiến lược 1939–1941: Vì sao quyết định này phản ánh năng lực lãnh đạo tài tình của Đảng?", "Đây là điểm mấu chốt để hiểu về Chuyển hướng chiến lược 1939–1941.", new[] { "Lựa chọn đúng về lịch sử Đảng 20", "Lựa chọn sai A 20", "Lựa chọn sai B 20", "Lựa chọn sai C 20" }, 0),
            (topics[topicNames[4]], "Easy", "Seed Q81 - Việt Minh và Cách mạng Tháng Tám 1945: Sự kiện nào diễn ra vào thời điểm 1?", "Đây là điểm mấu chốt để hiểu về Việt Minh và Cách mạng Tháng Tám 1945.", new[] { "Lựa chọn đúng về lịch sử Đảng 1", "Lựa chọn sai A 1", "Lựa chọn sai B 1", "Lựa chọn sai C 1" }, 0),
            (topics[topicNames[4]], "Easy", "Seed Q82 - Việt Minh và Cách mạng Tháng Tám 1945: Sự kiện nào diễn ra vào thời điểm 2?", "Đây là điểm mấu chốt để hiểu về Việt Minh và Cách mạng Tháng Tám 1945.", new[] { "Lựa chọn đúng về lịch sử Đảng 2", "Lựa chọn sai A 2", "Lựa chọn sai B 2", "Lựa chọn sai C 2" }, 0),
            (topics[topicNames[4]], "Easy", "Seed Q83 - Việt Minh và Cách mạng Tháng Tám 1945: Sự kiện nào diễn ra vào thời điểm 3?", "Đây là điểm mấu chốt để hiểu về Việt Minh và Cách mạng Tháng Tám 1945.", new[] { "Lựa chọn đúng về lịch sử Đảng 3", "Lựa chọn sai A 3", "Lựa chọn sai B 3", "Lựa chọn sai C 3" }, 0),
            (topics[topicNames[4]], "Easy", "Seed Q84 - Việt Minh và Cách mạng Tháng Tám 1945: Sự kiện nào diễn ra vào thời điểm 4?", "Đây là điểm mấu chốt để hiểu về Việt Minh và Cách mạng Tháng Tám 1945.", new[] { "Lựa chọn đúng về lịch sử Đảng 4", "Lựa chọn sai A 4", "Lựa chọn sai B 4", "Lựa chọn sai C 4" }, 0),
            (topics[topicNames[4]], "Easy", "Seed Q85 - Việt Minh và Cách mạng Tháng Tám 1945: Sự kiện nào diễn ra vào thời điểm 5?", "Đây là điểm mấu chốt để hiểu về Việt Minh và Cách mạng Tháng Tám 1945.", new[] { "Lựa chọn đúng về lịch sử Đảng 5", "Lựa chọn sai A 5", "Lựa chọn sai B 5", "Lựa chọn sai C 5" }, 0),
            (topics[topicNames[4]], "Easy", "Seed Q86 - Việt Minh và Cách mạng Tháng Tám 1945: Sự kiện nào diễn ra vào thời điểm 6?", "Đây là điểm mấu chốt để hiểu về Việt Minh và Cách mạng Tháng Tám 1945.", new[] { "Lựa chọn đúng về lịch sử Đảng 6", "Lựa chọn sai A 6", "Lựa chọn sai B 6", "Lựa chọn sai C 6" }, 0),
            (topics[topicNames[4]], "Easy", "Seed Q87 - Việt Minh và Cách mạng Tháng Tám 1945: Sự kiện nào diễn ra vào thời điểm 7?", "Đây là điểm mấu chốt để hiểu về Việt Minh và Cách mạng Tháng Tám 1945.", new[] { "Lựa chọn đúng về lịch sử Đảng 7", "Lựa chọn sai A 7", "Lựa chọn sai B 7", "Lựa chọn sai C 7" }, 0),
            (topics[topicNames[4]], "Medium", "Seed Q88 - Việt Minh và Cách mạng Tháng Tám 1945: Sự kiện tiêu biểu số 8 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Việt Minh và Cách mạng Tháng Tám 1945.", new[] { "Lựa chọn đúng về lịch sử Đảng 8", "Lựa chọn sai A 8", "Lựa chọn sai B 8", "Lựa chọn sai C 8" }, 0),
            (topics[topicNames[4]], "Medium", "Seed Q89 - Việt Minh và Cách mạng Tháng Tám 1945: Sự kiện tiêu biểu số 9 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Việt Minh và Cách mạng Tháng Tám 1945.", new[] { "Lựa chọn đúng về lịch sử Đảng 9", "Lựa chọn sai A 9", "Lựa chọn sai B 9", "Lựa chọn sai C 9" }, 0),
            (topics[topicNames[4]], "Medium", "Seed Q90 - Việt Minh và Cách mạng Tháng Tám 1945: Sự kiện tiêu biểu số 10 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Việt Minh và Cách mạng Tháng Tám 1945.", new[] { "Lựa chọn đúng về lịch sử Đảng 10", "Lựa chọn sai A 10", "Lựa chọn sai B 10", "Lựa chọn sai C 10" }, 0),
            (topics[topicNames[4]], "Medium", "Seed Q91 - Việt Minh và Cách mạng Tháng Tám 1945: Sự kiện tiêu biểu số 11 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Việt Minh và Cách mạng Tháng Tám 1945.", new[] { "Lựa chọn đúng về lịch sử Đảng 11", "Lựa chọn sai A 11", "Lựa chọn sai B 11", "Lựa chọn sai C 11" }, 0),
            (topics[topicNames[4]], "Medium", "Seed Q92 - Việt Minh và Cách mạng Tháng Tám 1945: Sự kiện tiêu biểu số 12 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Việt Minh và Cách mạng Tháng Tám 1945.", new[] { "Lựa chọn đúng về lịch sử Đảng 12", "Lựa chọn sai A 12", "Lựa chọn sai B 12", "Lựa chọn sai C 12" }, 0),
            (topics[topicNames[4]], "Medium", "Seed Q93 - Việt Minh và Cách mạng Tháng Tám 1945: Sự kiện tiêu biểu số 13 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Việt Minh và Cách mạng Tháng Tám 1945.", new[] { "Lựa chọn đúng về lịch sử Đảng 13", "Lựa chọn sai A 13", "Lựa chọn sai B 13", "Lựa chọn sai C 13" }, 0),
            (topics[topicNames[4]], "Medium", "Seed Q94 - Việt Minh và Cách mạng Tháng Tám 1945: Sự kiện tiêu biểu số 14 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Việt Minh và Cách mạng Tháng Tám 1945.", new[] { "Lựa chọn đúng về lịch sử Đảng 14", "Lựa chọn sai A 14", "Lựa chọn sai B 14", "Lựa chọn sai C 14" }, 0),
            (topics[topicNames[4]], "Medium", "Seed Q95 - Việt Minh và Cách mạng Tháng Tám 1945: Sự kiện tiêu biểu số 15 có ý nghĩa gì?", "Đây là điểm mấu chốt để hiểu về Việt Minh và Cách mạng Tháng Tám 1945.", new[] { "Lựa chọn đúng về lịch sử Đảng 15", "Lựa chọn sai A 15", "Lựa chọn sai B 15", "Lựa chọn sai C 15" }, 0),
            (topics[topicNames[4]], "Hard", "Seed Q96 - Việt Minh và Cách mạng Tháng Tám 1945: Vì sao quyết định này phản ánh năng lực lãnh đạo tài tình của Đảng?", "Đây là điểm mấu chốt để hiểu về Việt Minh và Cách mạng Tháng Tám 1945.", new[] { "Lựa chọn đúng về lịch sử Đảng 16", "Lựa chọn sai A 16", "Lựa chọn sai B 16", "Lựa chọn sai C 16" }, 0),
            (topics[topicNames[4]], "Hard", "Seed Q97 - Việt Minh và Cách mạng Tháng Tám 1945: Vì sao quyết định này phản ánh năng lực lãnh đạo tài tình của Đảng?", "Đây là điểm mấu chốt để hiểu về Việt Minh và Cách mạng Tháng Tám 1945.", new[] { "Lựa chọn đúng về lịch sử Đảng 17", "Lựa chọn sai A 17", "Lựa chọn sai B 17", "Lựa chọn sai C 17" }, 0),
            (topics[topicNames[4]], "Hard", "Seed Q98 - Việt Minh và Cách mạng Tháng Tám 1945: Vì sao quyết định này phản ánh năng lực lãnh đạo tài tình của Đảng?", "Đây là điểm mấu chốt để hiểu về Việt Minh và Cách mạng Tháng Tám 1945.", new[] { "Lựa chọn đúng về lịch sử Đảng 18", "Lựa chọn sai A 18", "Lựa chọn sai B 18", "Lựa chọn sai C 18" }, 0),
            (topics[topicNames[4]], "Hard", "Seed Q99 - Việt Minh và Cách mạng Tháng Tám 1945: Vì sao quyết định này phản ánh năng lực lãnh đạo tài tình của Đảng?", "Đây là điểm mấu chốt để hiểu về Việt Minh và Cách mạng Tháng Tám 1945.", new[] { "Lựa chọn đúng về lịch sử Đảng 19", "Lựa chọn sai A 19", "Lựa chọn sai B 19", "Lựa chọn sai C 19" }, 0),
            (topics[topicNames[4]], "Hard", "Seed Q100 - Việt Minh và Cách mạng Tháng Tám 1945: Vì sao quyết định này phản ánh năng lực lãnh đạo tài tình của Đảng?", "Đây là điểm mấu chốt để hiểu về Việt Minh và Cách mạng Tháng Tám 1945.", new[] { "Lựa chọn đúng về lịch sử Đảng 20", "Lựa chọn sai A 20", "Lựa chọn sai B 20", "Lựa chọn sai C 20" }, 0),
        };

        foreach (var (tid, diff, content, expl, opts, ci) in qs)
        {
            if (await _db.Questions.AnyAsync(q => q.Content == content)) continue;
            var q = new Question { TopicId = tid, Content = content, Explanation = expl, Difficulty = diff,
                BaseScore = diff == "Easy" ? 100 : diff == "Medium" ? 150 : 200,
                PenaltyHP = diff == "Easy" ? 10 : diff == "Medium" ? 15 : 20,
                TimeLimit = diff == "Easy" ? 15 : diff == "Medium" ? 20 : 25 };
            _db.Questions.Add(q);
            await _db.SaveChangesAsync();
            for (int i = 0; i < opts.Length; i++)
                _db.QuestionOptions.Add(new QuestionOption { QuestionId = q.Id, Text = opts[i], IsCorrect = i == ci });
            await _db.SaveChangesAsync();
        }
        return Ok(new { message = $"Done. Total: {await _db.Questions.CountAsync()}" });
    }
}
