// <auto-generated />
using System;
using AnimalTheoryRoyale.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnimalTheoryRoyale.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260603053421_SeedCharacters")]
    partial class SeedCharacters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnimalTheoryRoyale.Models.AnswerLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreEarned")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("AnswerLogs", (string)null);
                });

            modelBuilder.Entity("AnimalTheoryRoyale.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnimalType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HitboxSize")
                        .HasColumnType("integer");

                    b.Property<string>("IconPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InitialAmmo")
                        .HasColumnType("integer");

                    b.Property<int>("MaxHP")
                        .HasColumnType("integer");

                    b.Property<string>("ModelPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MoveSpeed")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SkillCooldown")
                        .HasColumnType("integer");

                    b.Property<string>("SkillDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SkillDuration")
                        .HasColumnType("integer");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Characters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimalType = "Tanker",
                            HitboxSize = 2,
                            IconPath = "",
                            InitialAmmo = 10,
                            MaxHP = 150,
                            ModelPath = "",
                            MoveSpeed = 60,
                            Name = "Voi",
                            SkillCooldown = 30,
                            SkillDescription = "",
                            SkillDuration = 0,
                            SkillName = "Lá Chắn Đại Ngàn"
                        },
                        new
                        {
                            Id = 2,
                            AnimalType = "Speedster",
                            HitboxSize = 1,
                            IconPath = "",
                            InitialAmmo = 8,
                            MaxHP = 80,
                            ModelPath = "",
                            MoveSpeed = 130,
                            Name = "Thỏ",
                            SkillCooldown = 25,
                            SkillDescription = "",
                            SkillDuration = 0,
                            SkillName = "Bứt Tốc"
                        },
                        new
                        {
                            Id = 3,
                            AnimalType = "Strategist",
                            HitboxSize = 1,
                            IconPath = "",
                            InitialAmmo = 10,
                            MaxHP = 100,
                            ModelPath = "",
                            MoveSpeed = 110,
                            Name = "Cáo",
                            SkillCooldown = 45,
                            SkillDescription = "",
                            SkillDuration = 0,
                            SkillName = "Mưu Trí"
                        },
                        new
                        {
                            Id = 4,
                            AnimalType = "Defender",
                            HitboxSize = 2,
                            IconPath = "",
                            InitialAmmo = 8,
                            MaxHP = 130,
                            ModelPath = "",
                            MoveSpeed = 65,
                            Name = "Rùa",
                            SkillCooldown = 35,
                            SkillDescription = "",
                            SkillDuration = 0,
                            SkillName = "Mai Rùa Bảo Vệ"
                        });
                });

            modelBuilder.Entity("AnimalTheoryRoyale.Models.GameResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FinalScore")
                        .HasColumnType("integer");

                    b.Property<int>("MaxCombo")
                        .HasColumnType("integer");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<int>("SurvivalTime")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("WrongCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("GameResults", (string)null);
                });

            modelBuilder.Entity("AnimalTheoryRoyale.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseScore")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PenaltyHP")
                        .HasColumnType("integer");

                    b.Property<int>("TimeLimit")
                        .HasColumnType("integer");

                    b.Property<int>("TopicId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("AnimalTheoryRoyale.Models.QuestionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionOptions", (string)null);
                });

            modelBuilder.Entity("AnimalTheoryRoyale.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GameDuration")
                        .HasColumnType("integer");

                    b.Property<int>("HostId")
                        .HasColumnType("integer");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HostId");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("AnimalTheoryRoyale.Models.RoomSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DifficultyMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EnableFruits")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableItems")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableWeapon")
                        .HasColumnType("boolean");

                    b.Property<int>("QuestionTopicId")
                        .HasColumnType("integer");

                    b.Property<string>("RespawnMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<string>("SafeZoneMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("RoomSettings", (string)null);
                });

            modelBuilder.Entity("AnimalTheoryRoyale.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Topics", (string)null);
                });

            modelBuilder.Entity("AnimalTheoryRoyale.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("XP")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("AnimalTheoryRoyale.Models.AnswerLog", b =>
                {
                    b.HasOne("AnimalTheoryRoyale.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnimalTheoryRoyale.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimalTheoryRoyale.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AnimalTheoryRoyale.Models.GameResult", b =>
                {
                    b.HasOne("AnimalTheoryRoyale.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnimalTheoryRoyale.Models.Room", "Room")
                        .WithMany("Results")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimalTheoryRoyale.Models.User", "User")
                        .WithMany("GameResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AnimalTheoryRoyale.Models.Question", b =>
                {
                    b.HasOne("AnimalTheoryRoyale.Models.Topic", "Topic")
                        .WithMany("Questions")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("AnimalTheoryRoyale.Models.QuestionOption", b =>
                {
                    b.HasOne("AnimalTheoryRoyale.Models.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("AnimalTheoryRoyale.Models.Room", b =>
                {
                    b.HasOne("AnimalTheoryRoyale.Models.User", "Host")
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Host");
                });

            modelBuilder.Entity("AnimalTheoryRoyale.Models.RoomSetting", b =>
                {
                    b.HasOne("AnimalTheoryRoyale.Models.Room", "Room")
                        .WithOne("Setting")
                        .HasForeignKey("AnimalTheoryRoyale.Models.RoomSetting", "RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("AnimalTheoryRoyale.Models.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("AnimalTheoryRoyale.Models.Room", b =>
                {
                    b.Navigation("Results");

                    b.Navigation("Setting");
                });

            modelBuilder.Entity("AnimalTheoryRoyale.Models.Topic", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("AnimalTheoryRoyale.Models.User", b =>
                {
                    b.Navigation("GameResults");
                });
#pragma warning restore 612, 618
        }
    }
}
