import fs from 'fs';
import path from 'path';

const timelineEvents = [
  {
    id: "truoc-1911",
    period: "Trước năm 1911",
    title: "Cội nguồn hình thành tư tưởng",
    shortDescription: "Bối cảnh xã hội và truyền thống gia đình, quê hương.",
    historicalContext: "Việt Nam cuối thế kỷ XIX - đầu thế kỷ XX bị thực dân Pháp xâm lược. Các phong trào yêu nước theo khuynh hướng phong kiến và tư sản đều thất bại.",
    problem: "Làm thế nào để tìm ra con đường cứu nước giải phóng dân tộc khi các phong trào cũ đều bế tắc?",
    ideologicalDevelopment: "Hình thành chí hướng cứu nước ban đầu, tiếp thu truyền thống yêu nước, nhân nghĩa, đoàn kết của dân tộc.",
    impact: "Tạo tiền đề tư tưởng vững chắc để Hồ Chí Minh quyết định ra đi tìm đường cứu nước.",
    learningValue: "Hiểu được tầm quan trọng của truyền thống dân tộc và lòng yêu nước.",
    relatedChapterIds: ["chuong-2"],
    relatedConceptIds: ["truyen-thong-dan-toc", "boi-canh-dan-toc", "doc-lap-dan-toc"],
    keyQuestions: ["Vì sao các phong trào yêu nước cuối thế kỷ XIX đều thất bại?"],
    requiresVerification: true
  },
  {
    id: "ra-di-tim-duong-cuu-nuoc-1911",
    period: "1911",
    title: "Ra đi tìm đường cứu nước",
    shortDescription: "Nguyễn Tất Thành ra đi tìm con đường giải phóng dân tộc mới.",
    historicalContext: "Ngày 5/6/1911, Nguyễn Tất Thành rời bến cảng Nhà Rồng trên con tàu Amiral Latouche-Tréville.",
    problem: "Cần tìm hiểu xem các nước phương Tây làm thế nào để về giúp đồng bào mình.",
    ideologicalDevelopment: "Thể hiện tư duy độc lập, không đi theo lối mòn của các bậc tiền bối, lựa chọn khảo nghiệm thực tiễn thế giới.",
    impact: "Mở ra bước ngoặt trong hành trình tìm đường cứu nước.",
    learningValue: "Học tập tư duy độc lập, sáng tạo, dám nghĩ dám làm.",
    relatedChapterIds: ["chuong-2", "chuong-3"],
    relatedConceptIds: ["cach-mang-giai-phong-dan-toc", "doc-lap-dan-toc", "thong-nhat-ly-luan-va-thuc-tien"],
    keyQuestions: ["Vì sao Nguyễn Tất Thành lựa chọn ra đi tìm đường cứu nước ở phương Tây?"],
    requiresVerification: true
  },
  {
    id: "khao-nghiem-thuc-tien-1911-1920",
    period: "1911 - 1920",
    title: "Khảo nghiệm thực tiễn thế giới",
    shortDescription: "Đi qua nhiều quốc gia để tìm hiểu bản chất chủ nghĩa đế quốc.",
    historicalContext: "Chiến tranh thế giới thứ nhất bùng nổ, phong trào công nhân quốc tế phát triển mạnh mẽ.",
    problem: "Bản chất thực sự của các khẩu hiệu Tự do - Bình đẳng - Bác ái là gì?",
    ideologicalDevelopment: "Nhận thức sâu sắc rằng ở đâu nhân dân lao động cũng bị bóc lột, ở đâu chủ nghĩa đế quốc cũng tàn bạo.",
    impact: "Hình thành tình cảm giai cấp, nhận thức được sự cần thiết phải kết hợp sức mạnh dân tộc và thời đại.",
    learningValue: "Rút ra bài học về tầm quan trọng của việc nghiên cứu thực tiễn sâu sát.",
    relatedChapterIds: ["chuong-2"],
    relatedConceptIds: ["boi-canh-thoi-dai", "thong-nhat-ly-luan-va-thuc-tien", "suc-manh-dan-toc-va-thoi-dai"],
    keyQuestions: ["Hồ Chí Minh đã rút ra bài học gì từ cuộc khảo nghiệm thực tiễn này?"],
    requiresVerification: true
  },
  {
    id: "yeu-sach-1919",
    period: "1919",
    title: "Gửi Yêu sách của nhân dân An Nam",
    shortDescription: "Gửi bản yêu sách tới Hội nghị Versailles.",
    historicalContext: "Hội nghị Versailles họp để phân chia lại thế giới sau CTTG I.",
    problem: "Đấu tranh đòi các quyền tự do, dân chủ cơ bản cho nhân dân Việt Nam bằng phương pháp hòa bình.",
    ideologicalDevelopment: "Thể hiện bước phát triển về nhận thức quyền dân tộc, quyền tự do, dân chủ.",
    impact: "Tạo tiếng vang lớn, đồng thời nhận ra bản chất lừa bịp của chủ nghĩa đế quốc, khẳng định phải dựa vào sức mình là chính.",
    learningValue: "Hiểu được giới hạn của các phương pháp đấu tranh cải lương.",
    relatedChapterIds: ["chuong-2"],
    relatedConceptIds: ["doc-lap-dan-toc", "cach-mang-giai-phong-dan-toc", "boi-canh-thoi-dai"],
    keyQuestions: ["Vì sao việc gửi Bản yêu sách lại là một bước tiến quan trọng?"],
    requiresVerification: true
  },
  {
    id: "tiep-can-mac-lenin-1920",
    period: "1920",
    title: "Tiếp cận chủ nghĩa Mác - Lênin",
    shortDescription: "Đọc Luận cương của Lênin về vấn đề dân tộc và thuộc địa.",
    historicalContext: "Đại hội lần thứ 18 Đảng Xã hội Pháp tại Tours.",
    problem: "Xác định con đường giải phóng dân tộc triệt để nhất.",
    ideologicalDevelopment: "Chuyển biến từ chủ nghĩa yêu nước đến chủ nghĩa Mác - Lênin. Xác định cách mạng giải phóng dân tộc phải đi theo con đường cách mạng vô sản.",
    impact: "Bước ngoặt lớn nhất trong cuộc đời hoạt động cách mạng của Hồ Chí Minh.",
    learningValue: "Sự kết hợp giữa lý luận tiên tiến và thực tiễn cách mạng.",
    relatedChapterIds: ["chuong-2", "chuong-3"],
    relatedConceptIds: ["chu-nghia-mac-lenin", "doc-lap-dan-toc-gan-lien-cnxh", "cach-mang-giai-phong-dan-toc"],
    keyQuestions: ["Luận cương của Lênin đã giải quyết vấn đề gì cho Nguyễn Ái Quốc?"],
    requiresVerification: true
  },
  {
    id: "chuan-bi-thanh-lap-dang-1921-1930",
    period: "1921 - 1930",
    title: "Chuẩn bị về tư tưởng, chính trị, tổ chức",
    shortDescription: "Truyền bá chủ nghĩa Mác - Lênin vào phong trào cách mạng Việt Nam.",
    historicalContext: "Phong trào công nhân và phong trào yêu nước Việt Nam đang cần một đường lối lãnh đạo đúng đắn.",
    problem: "Làm thế nào để kết hợp chủ nghĩa Mác-Lênin với phong trào trong nước để thành lập Đảng?",
    ideologicalDevelopment: "Hình thành các luận điểm cơ bản về cách mạng giải phóng dân tộc, chuẩn bị các điều kiện cho sự ra đời của Đảng.",
    impact: "Tạo cơ sở chín muồi cho việc thành lập Đảng Cộng sản Việt Nam.",
    learningValue: "Tầm quan trọng của sự chuẩn bị kỹ lưỡng về lý luận và tổ chức.",
    relatedChapterIds: ["chuong-2", "chuong-4"],
    relatedConceptIds: ["dang-cong-san-viet-nam", "chu-nghia-mac-lenin", "cach-mang-giai-phong-dan-toc"],
    keyQuestions: ["Hồ Chí Minh đã chuẩn bị những gì cho sự ra đời của Đảng?"],
    requiresVerification: true
  },
  {
    id: "hoi-viet-nam-cach-mang-thanh-nien-1925",
    period: "1925",
    title: "Thành lập Hội Việt Nam Cách mạng Thanh niên",
    shortDescription: "Tổ chức tiền thân của Đảng Cộng sản Việt Nam.",
    historicalContext: "Phong trào yêu nước tại Quảng Châu (Trung Quốc) đang phát triển.",
    problem: "Cần một tổ chức để huấn luyện cán bộ và truyền bá lý luận về nước.",
    ideologicalDevelopment: "Sáng tạo trong việc xây dựng một tổ chức quá độ để chuẩn bị tiến tới thành lập Đảng.",
    impact: "Đào tạo được hạt nhân lãnh đạo và truyền bá mạnh mẽ lý luận cách mạng.",
    learningValue: "Bài học về cách tổ chức và phát triển phong trào từ những bước quá độ phù hợp.",
    relatedChapterIds: ["chuong-4"],
    relatedConceptIds: ["can-bo", "dang-cong-san-viet-nam", "xay-dung-dang"],
    keyQuestions: ["Vai trò của Hội Việt Nam Cách mạng Thanh niên là gì?"],
    requiresVerification: true
  },
  {
    id: "duong-kach-menh-1927",
    period: "1927",
    title: "Tác phẩm Đường Kách mệnh",
    shortDescription: "Hệ thống hóa lý luận cơ bản của cách mạng Việt Nam.",
    historicalContext: "Bài giảng của Hồ Chí Minh tại các lớp huấn luyện cán bộ ở Quảng Châu được tập hợp lại.",
    problem: "Cung cấp tài liệu lý luận mang tính định hướng rõ ràng cho cán bộ cách mạng.",
    ideologicalDevelopment: "Hệ thống hóa lý luận về cách mạng giải phóng dân tộc, đặc biệt nhấn mạnh tư cách người cách mạng.",
    impact: "Cuốn sách giáo khoa đầu tiên của cách mạng Việt Nam.",
    learningValue: "Sự thống nhất giữa đạo đức và tài năng của người cán bộ.",
    relatedChapterIds: ["chuong-4", "chuong-6"],
    relatedConceptIds: ["dao-duc-cach-mang", "dang-cong-san-viet-nam", "can-bo"],
    keyQuestions: ["Tác phẩm Đường Kách mệnh đóng vai trò gì trong việc chuẩn bị thành lập Đảng?"],
    requiresVerification: true
  },
  {
    id: "thanh-lap-dang-1930",
    period: "1930",
    title: "Thành lập Đảng Cộng sản Việt Nam",
    shortDescription: "Thống nhất các tổ chức cộng sản thành Đảng Cộng sản Việt Nam.",
    historicalContext: "Đầu năm 1930, phong trào cộng sản trong nước bị chia rẽ thành nhiều tổ chức.",
    problem: "Phải chấm dứt sự chia rẽ để tạo sức mạnh thống nhất lãnh đạo toàn quốc.",
    ideologicalDevelopment: "Sáng tạo trong quy luật ra đời của Đảng: kết hợp chủ nghĩa Mác-Lênin với phong trào công nhân và phong trào yêu nước.",
    impact: "Đánh dấu bước ngoặt vĩ đại của cách mạng Việt Nam, chấm dứt khủng hoảng về đường lối.",
    learningValue: "Hiểu được tính tất yếu khách quan và sức mạnh của khối đại đoàn kết nội bộ.",
    relatedChapterIds: ["chuong-4"],
    relatedConceptIds: ["dang-cong-san-viet-nam", "xay-dung-dang", "cach-mang-giai-phong-dan-toc"],
    keyQuestions: ["Sự kiện này đã giải quyết cuộc khủng hoảng nào của cách mạng Việt Nam?"],
    requiresVerification: true
  },
  {
    id: "phat-trien-tu-tuong-1930-1945",
    period: "1930 - 1945",
    title: "Phát triển tư tưởng giải phóng dân tộc",
    shortDescription: "Đặt nhiệm vụ giải phóng dân tộc lên hàng đầu.",
    historicalContext: "Cao trào cách mạng 1930-1931, 1936-1939 và Chiến tranh thế giới thứ hai bùng nổ.",
    problem: "Điều chỉnh chiến lược cách mạng phù hợp với bối cảnh thế giới và trong nước.",
    ideologicalDevelopment: "Khẳng định giải phóng dân tộc là nhiệm vụ cấp bách nhất, tạm gác khẩu hiệu cách mạng ruộng đất.",
    impact: "Quyết định đến sự thành công của Cách mạng Tháng Tám.",
    learningValue: "Sự linh hoạt trong chiến lược và kiên định về nguyên tắc.",
    relatedChapterIds: ["chuong-3", "chuong-5"],
    relatedConceptIds: ["doc-lap-dan-toc", "dai-doan-ket", "cach-mang-giai-phong-dan-toc"],
    keyQuestions: ["Vì sao Hồ Chí Minh quyết định đặt nhiệm vụ giải phóng dân tộc lên hàng đầu?"],
    requiresVerification: true
  },
  {
    id: "ve-nuoc-1941",
    period: "1941",
    title: "Về nước trực tiếp lãnh đạo",
    shortDescription: "Hồ Chí Minh về nước xây dựng căn cứ địa và Mặt trận Việt Minh.",
    historicalContext: "Sau 30 năm bôn ba, Hồ Chí Minh trở về Pác Bó (Cao Bằng) trực tiếp lãnh đạo phong trào.",
    problem: "Cần xây dựng lực lượng vũ trang và chính trị rộng lớn để chuẩn bị khởi nghĩa.",
    ideologicalDevelopment: "Hoàn chỉnh đường lối giải phóng dân tộc, thành lập Mặt trận Việt Minh để phát huy đại đoàn kết.",
    impact: "Tạo ra một cao trào cứu nước mạnh mẽ, chuẩn bị trực tiếp cho Tổng khởi nghĩa.",
    learningValue: "Sức mạnh vô địch của đại đoàn kết dân tộc.",
    relatedChapterIds: ["chuong-5"],
    relatedConceptIds: ["dai-doan-ket", "mat-tran-dan-toc-thong-nhat", "doc-lap-dan-toc"],
    keyQuestions: ["Vai trò của Mặt trận Việt Minh là gì?"],
    requiresVerification: true
  },
  {
    id: "cach-mang-thang-tam-1945",
    period: "1945",
    title: "Cách mạng Tháng Tám & Tuyên ngôn",
    shortDescription: "Thắng lợi của CMT8, khai sinh nước VNDCCH.",
    historicalContext: "Nhật đầu hàng Đồng minh, tạo thời cơ 'ngàn năm có một'.",
    problem: "Chớp thời cơ để giành chính quyền trước khi quân Đồng minh vào Đông Dương.",
    ideologicalDevelopment: "Hiện thực hóa khát vọng độc lập tự do, thiết lập Nhà nước của dân, do dân, vì dân.",
    impact: "Kết thúc hơn 80 năm đô hộ của thực dân Pháp, đưa dân tộc Việt Nam sang kỷ nguyên độc lập.",
    learningValue: "Bài học về chớp thời cơ và sức mạnh toàn dân nổi dậy.",
    relatedChapterIds: ["chuong-3", "chuong-4"],
    relatedConceptIds: ["doc-lap-dan-toc", "nha-nuoc-cua-dan", "nhan-dan-lam-chu"],
    keyQuestions: ["Tuyên ngôn Độc lập mang ý nghĩa lịch sử như thế nào?"],
    requiresVerification: true
  },
  {
    id: "khang-chien-kien-quoc-1945-1954",
    period: "1945 - 1954",
    title: "Kháng chiến và kiến quốc",
    shortDescription: "Vừa chiến đấu bảo vệ độc lập, vừa xây dựng chế độ mới.",
    historicalContext: "Nước VNDCCH non trẻ đối mặt với thù trong giặc ngoài (Pháp tái chiếm).",
    problem: "Bảo vệ nền độc lập đồng thời xây dựng chính quyền, giải quyết nạn đói, dốt.",
    ideologicalDevelopment: "Tư tưởng kết hợp kháng chiến với kiến quốc, chiến tranh nhân dân, toàn dân toàn diện.",
    impact: "Bảo vệ thành công chính quyền, đỉnh cao là chiến thắng Điện Biên Phủ 1954.",
    learningValue: "Tinh thần tự lực tự cường và ý chí bảo vệ nền độc lập.",
    relatedChapterIds: ["chuong-4", "chuong-5"],
    relatedConceptIds: ["nha-nuoc-cua-dan", "nha-nuoc-do-dan", "nha-nuoc-vi-dan", "dai-doan-ket"],
    keyQuestions: ["Vì sao phải thực hiện kháng chiến toàn dân, toàn diện?"],
    requiresVerification: true
  },
  {
    id: "xay-dung-cnxh-1954-1969",
    period: "1954 - 1969",
    title: "Xây dựng CNXH & Đấu tranh thống nhất",
    shortDescription: "Miền Bắc xây dựng CNXH, miền Nam tiếp tục chống Mỹ.",
    historicalContext: "Đất nước tạm thời chia cắt làm hai miền.",
    problem: "Thực hiện đồng thời hai nhiệm vụ chiến lược ở hai miền.",
    ideologicalDevelopment: "Phát triển tư tưởng về CNXH, coi CNXH là cơ sở bảo đảm cho độc lập tự do. Gắn xây dựng con người với phát triển kinh tế.",
    impact: "Miền Bắc trở thành hậu phương lớn, chi viện cho tiền tuyến miền Nam.",
    learningValue: "Mối liên hệ biện chứng giữa độc lập dân tộc và chủ nghĩa xã hội.",
    relatedChapterIds: ["chuong-3", "chuong-6"],
    relatedConceptIds: ["chu-nghia-xa-hoi", "doc-lap-dan-toc-gan-lien-cnxh", "dao-duc-cach-mang", "van-hoa", "con-nguoi"],
    keyQuestions: ["Đặc trưng nổi bật của CNXH theo tư tưởng Hồ Chí Minh là gì?"],
    requiresVerification: true
  },
  {
    id: "di-chuc-1969",
    period: "1969",
    title: "Di chúc Hồ Chí Minh",
    shortDescription: "Tài liệu mang giá trị lịch sử và định hướng lâu dài.",
    historicalContext: "Bác Hồ qua đời ngày 2/9/1969 để lại bản Di chúc thiêng liêng.",
    problem: "Căn dặn những việc cần làm sau khi kháng chiến thành công.",
    ideologicalDevelopment: "Kết tinh toàn bộ tư tưởng về Đảng, nhân dân, đoàn kết, và chăm lo cho con người.",
    impact: "Là di sản tinh thần vô giá, định hướng cho công cuộc xây dựng và bảo vệ tổ quốc.",
    learningValue: "Tình yêu thương con người và trách nhiệm lớn lao đối với dân tộc.",
    relatedChapterIds: ["chuong-4", "chuong-5", "chuong-6"],
    relatedConceptIds: ["xay-dung-dang", "dao-duc-cach-mang", "con-nguoi", "dai-doan-ket"],
    keyQuestions: ["Trong Di chúc, Bác căn dặn điều gì về công tác xây dựng Đảng?"],
    requiresVerification: true
  },
  {
    id: "hien-nay",
    period: "Hiện nay",
    title: "Giá trị vận dụng trong thời đại mới",
    shortDescription: "Sức sống mãnh liệt của tư tưởng Hồ Chí Minh hiện nay.",
    historicalContext: "Thế kỷ XXI, thời đại toàn cầu hóa và cách mạng công nghiệp 4.0.",
    problem: "Vận dụng tư tưởng HCM để giải quyết các vấn đề đương đại.",
    ideologicalDevelopment: "Tư tưởng HCM vẫn là nền tảng tư tưởng, kim chỉ nam cho hành động của Đảng và nhân dân.",
    impact: "Giúp giữ vững định hướng XHCN, phát triển văn hóa, con người Việt Nam.",
    learningValue: "Ứng dụng vào học tập, rèn luyện đạo đức, trách nhiệm công dân.",
    relatedChapterIds: ["chuong-1", "chuong-6"],
    relatedConceptIds: ["y-nghia-hoc-tap", "trach-nhiem-cong-dan", "dao-duc-cach-mang", "van-hoa-so", "ban-sac-dan-toc"],
    keyQuestions: ["Sinh viên cần vận dụng tư tưởng Hồ Chí Minh như thế nào trong thời đại số?"],
    requiresVerification: true
  }
];

const fileContent = `export const timelineEvents = ${JSON.stringify(timelineEvents, null, 2)};\n`;

const __dirname = path.resolve();
fs.writeFileSync(path.join(__dirname, 'src/data/timelineData.js'), fileContent, 'utf-8');
console.log('timelineData.js generated.');
