CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529055834_InitialCreate') THEN
    CREATE TABLE "Characters" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "AnimalType" text NOT NULL,
        "MaxHP" integer NOT NULL,
        "MoveSpeed" integer NOT NULL,
        "HitboxSize" integer NOT NULL,
        "InitialAmmo" integer NOT NULL,
        "SkillName" text NOT NULL,
        "SkillDescription" text NOT NULL,
        "SkillCooldown" integer NOT NULL,
        "SkillDuration" integer NOT NULL,
        "ModelPath" text NOT NULL,
        "IconPath" text NOT NULL,
        CONSTRAINT "PK_Characters" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529055834_InitialCreate') THEN
    CREATE TABLE "Topics" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Description" text NOT NULL,
        CONSTRAINT "PK_Topics" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529055834_InitialCreate') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Username" text NOT NULL,
        "PasswordHash" text NOT NULL,
        "Role" text NOT NULL,
        "XP" integer NOT NULL,
        "Level" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529055834_InitialCreate') THEN
    CREATE TABLE "Questions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TopicId" integer NOT NULL,
        "Difficulty" text NOT NULL,
        "Content" text NOT NULL,
        "Explanation" text NOT NULL,
        "BaseScore" integer NOT NULL,
        "PenaltyHP" integer NOT NULL,
        "TimeLimit" integer NOT NULL,
        CONSTRAINT "PK_Questions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Questions_Topics_TopicId" FOREIGN KEY ("TopicId") REFERENCES "Topics" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529055834_InitialCreate') THEN
    CREATE TABLE "Rooms" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" text NOT NULL,
        "HostId" integer NOT NULL,
        "Status" text NOT NULL,
        "MaxPlayers" integer NOT NULL,
        "GameDuration" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "StartedAt" timestamp with time zone,
        "EndedAt" timestamp with time zone,
        CONSTRAINT "PK_Rooms" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Rooms_Users_HostId" FOREIGN KEY ("HostId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529055834_InitialCreate') THEN
    CREATE TABLE "QuestionOptions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "QuestionId" integer NOT NULL,
        "Text" text NOT NULL,
        "IsCorrect" boolean NOT NULL,
        CONSTRAINT "PK_QuestionOptions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_QuestionOptions_Questions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES "Questions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529055834_InitialCreate') THEN
    CREATE TABLE "AnswerLogs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoomId" integer NOT NULL,
        "UserId" integer NOT NULL,
        "QuestionId" integer NOT NULL,
        "IsCorrect" boolean NOT NULL,
        "ScoreEarned" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_AnswerLogs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AnswerLogs_Questions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES "Questions" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_AnswerLogs_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AnswerLogs_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529055834_InitialCreate') THEN
    CREATE TABLE "GameResults" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoomId" integer NOT NULL,
        "UserId" integer NOT NULL,
        "CharacterId" integer NOT NULL,
        "FinalScore" integer NOT NULL,
        "CorrectCount" integer NOT NULL,
        "WrongCount" integer NOT NULL,
        "MaxCombo" integer NOT NULL,
        "SurvivalTime" integer NOT NULL,
        "Rank" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_GameResults" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_GameResults_Characters_CharacterId" FOREIGN KEY ("CharacterId") REFERENCES "Characters" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_GameResults_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_GameResults_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529055834_InitialCreate') THEN
    CREATE TABLE "RoomSettings" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoomId" integer NOT NULL,
        "QuestionTopicId" integer NOT NULL,
        "DifficultyMode" text NOT NULL,
        "EnableWeapon" boolean NOT NULL,
        "EnableFruits" boolean NOT NULL,
        "EnableItems" boolean NOT NULL,
        "SafeZoneMode" text NOT NULL,
        "RespawnMode" text NOT NULL,
        CONSTRAINT "PK_RoomSettings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RoomSettings_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529055834_InitialCreate') THEN
    CREATE INDEX "IX_AnswerLogs_QuestionId" ON "AnswerLogs" ("QuestionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529055834_InitialCreate') THEN
    CREATE INDEX "IX_AnswerLogs_RoomId" ON "AnswerLogs" ("RoomId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529055834_InitialCreate') THEN
    CREATE INDEX "IX_AnswerLogs_UserId" ON "AnswerLogs" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529055834_InitialCreate') THEN
    CREATE INDEX "IX_GameResults_CharacterId" ON "GameResults" ("CharacterId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529055834_InitialCreate') THEN
    CREATE INDEX "IX_GameResults_RoomId" ON "GameResults" ("RoomId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529055834_InitialCreate') THEN
    CREATE INDEX "IX_GameResults_UserId" ON "GameResults" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529055834_InitialCreate') THEN
    CREATE INDEX "IX_QuestionOptions_QuestionId" ON "QuestionOptions" ("QuestionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529055834_InitialCreate') THEN
    CREATE INDEX "IX_Questions_TopicId" ON "Questions" ("TopicId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529055834_InitialCreate') THEN
    CREATE INDEX "IX_Rooms_HostId" ON "Rooms" ("HostId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529055834_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_RoomSettings_RoomId" ON "RoomSettings" ("RoomId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529055834_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260529055834_InitialCreate', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603050427_UpdateSchema') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260603050427_UpdateSchema', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603053421_SeedCharacters') THEN

                    INSERT INTO "Characters" ("Id", "AnimalType", "HitboxSize", "IconPath", "InitialAmmo", "MaxHP", "ModelPath", "MoveSpeed", "Name", "SkillCooldown", "SkillDescription", "SkillDuration", "SkillName")
                    VALUES 
                    (1, 'Tanker', 2, '', 10, 150, '', 60, 'Voi', 30, '', 0, 'Lá Chắn Đại Ngàn'),
                    (2, 'Speedster', 1, '', 8, 80, '', 130, 'Thỏ', 25, '', 0, 'Bứt Tốc'),
                    (3, 'Strategist', 1, '', 10, 100, '', 110, 'Cáo', 45, '', 0, 'Mưu Trí'),
                    (4, 'Defender', 2, '', 8, 130, '', 65, 'Rùa', 35, '', 0, 'Mai Rùa Bảo Vệ')
                    ON CONFLICT ("Id") DO NOTHING;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603053421_SeedCharacters') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260603053421_SeedCharacters', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610185057_Phase3_AddQuestionTypeAndPayload') THEN

                    ALTER TABLE "Questions" 
                    ADD COLUMN IF NOT EXISTS "ChallengePayloadJson" text NULL;

                    ALTER TABLE "Questions" 
                    ADD COLUMN IF NOT EXISTS "Type" text NOT NULL DEFAULT '';
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610185057_Phase3_AddQuestionTypeAndPayload') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260610185057_Phase3_AddQuestionTypeAndPayload', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610191409_AddQuestionChallengeFields') THEN

                    ALTER TABLE "Questions"
                    ADD COLUMN IF NOT EXISTS "QuestionType" text NOT NULL DEFAULT 'MultipleChoice';

                    ALTER TABLE "Questions"
                    ADD COLUMN IF NOT EXISTS "ChallengePayloadJson" text NULL;

                    ALTER TABLE "Questions"
                    ADD COLUMN IF NOT EXISTS "Explanation" text NULL;

                    ALTER TABLE "Questions"
                    ADD COLUMN IF NOT EXISTS "TimeLimit" integer NOT NULL DEFAULT 20;

                    ALTER TABLE "Questions"
                    ADD COLUMN IF NOT EXISTS "Difficulty" text NOT NULL DEFAULT 'Normal';

                    UPDATE "Questions"
                    SET "QuestionType" = 'MultipleChoice'
                    WHERE "QuestionType" IS NULL OR "QuestionType" = '';
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260610191409_AddQuestionChallengeFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260610191409_AddQuestionChallengeFields', '8.0.0');
    END IF;
END $EF$;
COMMIT;



-- MANUAL FIXES FOR SUPABASE --
ALTER TABLE "Questions" ALTER COLUMN "ChallengePayloadJson" DROP NOT NULL;
ALTER TABLE "Questions" ALTER COLUMN "Explanation" DROP NOT NULL;
